### ISSUE TITLE
Broken with CTP6

### ISSUE THREAD

**Issue by jwooley** [DotNetAnalyzers/TSqlAnalyzer#14]
Analyzer is not recognized with VS 2015 CTP6.

**Comment by ErikEJ** [comment]
Thanks! Do you have a PR ready?

**Comment by jwooley** [comment]
Not yet. I just pulled a clone, but not sure if I'll have much time over the next week to create a PR.

**Comment by ErikEJ** [comment]
I will boot an Azure VM, and see what I can do, @jwooley

**Comment by dothenrik** [comment]
I can fix the code but I don't use Git.

**Comment by ErikEJ** [comment]
@dothenrik if you can fix, email me changes, and I will update repo and new nuget package

**Comment by ErikEJ** [comment]
Attempt to fiox for CTP6 and uploaded new NuGet package (tests still need fixing)

**Comment by jwooley** [comment]
Looks like there are issues with the hint path (to your local folder) for the SQL ScriptDOM library. Also, the interpolated string test is failing due to changes in C#6 interpolation implementation. I have a fix, but get a 403 trying to push. I didn't fork before trying the changes.

**Comment by sharwell** [comment]
Hi Jim,

It's not too late to fork the repository now. In fact, it's normal and common for a single working folder on your computer to point to two or more different locations where the code is stored remotely. For your purposes, I believe the following steps are the easiest since you already cloned this GitHub repository.

1. Using the GitHub web interface, click Fork at the top right and fork this repository to your username.

2. On your computer from a command prompt, run the following command:

    ```bash
    git remote -v
    ```

3. **If** the previous command listed the `origin` remote as starting with `git@github.com:DotNetAnalyzers`, run the following command:

    ```bash
    git remote set-url origin git@github.com:jwooley/TSqlAnalyzer.git
    ```

4. **Otherwise**, if the previous command listed the `origin` remote as starting with `https://github.com/DotNetAnalyzers`, run the following command:

    ```bash
    git remote set-url origin https://github.com/jwooley/TSqlAnalyzer.git
    ```

After the above steps, when you push your code, it will push to your fork instead of trying to push to this repository (which you do have permissions for). :+1:
